# @Author: Danilo Diaz Valencia
# @Date:   2022-02-18 11:10:54
# @Last Modified by:   Danilo Diaz Valencia
# @Last Modified time: 2022-02-18 14:56:12
data:
  url: https://mach-eight.uc.r.appspot.com/
  
export:
  output_dir: reports
